//! Rust bindings for tree-sitter-wyn
//!
//! This crate provides Rust bindings for the Tree-sitter grammar for the Wyn
//! shader programming language.

use tree_sitter_language::LanguageFn;

extern "C" {
    fn tree_sitter_wyn() -> *const ();
}

/// Returns the tree-sitter Language for Wyn.
///
/// The returned pointer can be used with [`tree_sitter::Language`] to parse
/// Wyn source code.
///
/// # Example
///
/// ```
/// let language = tree_sitter_wyn::LANGUAGE;
/// let mut parser = tree_sitter::Parser::new();
/// parser.set_language(&language.into()).expect("Error loading Wyn grammar");
///
/// let source = "def add(x: i32, y: i32) i32 = x + y";
/// let tree = parser.parse(source, None).unwrap();
/// assert!(!tree.root_node().has_error());
/// ```
pub const LANGUAGE: LanguageFn = unsafe { LanguageFn::from_raw(tree_sitter_wyn) };

/// The source of the Wyn tree-sitter grammar.
pub const GRAMMAR: &str = include_str!("../../grammar.js");

/// The syntax highlighting query for Wyn.
pub const HIGHLIGHTS_QUERY: &str = include_str!("../../queries/highlights.scm");

/// The local definitions query for Wyn.
pub const LOCALS_QUERY: &str = include_str!("../../queries/locals.scm");

/// The content of the [`node-types.json`] file for this grammar.
///
/// This is generated by tree-sitter and contains information about the
/// grammar's node types.
pub const NODE_TYPES: &str = include_str!("../../src/node-types.json");

#[cfg(test)]
#[path = "lib_tests.rs"]
mod tests;
