// Emit the single Aileron module from both checked-in renderer metadata files.
// Node >=18. Also called after either offline asset generator completes.
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createHash } from 'node:crypto';

export function generateFont(root) {
  const load = name => JSON.parse(readFileSync(resolve(root, 'assets', name)));
  const atlas = load('aileron-mtsdf.json'), outlines = load('aileron-slug.json');
  const fontHash = createHash('sha256').update(readFileSync(resolve(root, 'assets/Aileron-Regular.otf'))).digest('hex');
  if (outlines.fontSha256 !== fontHash) throw new Error('Slug metadata font checksum mismatch');
  if (atlas.atlas.yOrigin !== 'top' || atlas.atlas.type !== 'mtsdf') throw new Error('Unexpected atlas format');
  const glyphs = [...atlas.glyphs].sort((a,b) => a.unicode-b.unicode);
  const curves = new Map(outlines.glyphs.map(g => [g.unicode,g]));
  if (glyphs.length !== curves.size) throw new Error('Renderer glyph subsets differ; regenerate both assets');
  const f = value => {
    const n = Math.fround(value);
    if (!Number.isFinite(n)) throw new Error('Non-finite font metadata');
    const s = n.toPrecision(9).replace(/(\.\d*?[1-9])0+(?=e|$)/,'$1').replace(/\.0+(?=e|$)/,'');
    return `${s.includes('.') || s.includes('e') ? s : s+'.0'}f32`;
  };
  const v = xs => `@[${xs.map(f).join(', ')}]`;
  const {width,height} = atlas.atlas;
  const records = glyphs.map(g => {
    const outline = curves.get(g.unicode), p = g.planeBounds, a = g.atlasBounds;
    if (!outline || Math.fround(g.advance) !== Math.fround(outline.advance))
      throw new Error(`Renderer metrics differ for ${g.unicode}; regenerate both assets`);
    return `    {advance = ${f(g.advance)}, plane = ${v(p ? [p.left,p.top,p.right,p.bottom] : [0,0,0,0])}, uv = ${v(a ? [a.left/width,a.top/height,a.right/width,a.bottom/height] : [0,0,0,0])}, bounds = ${v(outline.bounds)}, band_transform = ${v(outline.bandTransform)}, bands = @[${outline.bands.join(', ')}]}`;
  }).join(',\n');
  const fallback = glyphs.findIndex(g => g.unicode === 63);
  if (fallback < 0 || glyphs[0].unicode !== 32) throw new Error('Expected space and question-mark glyphs');
  const latin = Array.from({length:256},(_,cp)=>glyphs.findIndex(g=>g.unicode===cp));
  const extra = glyphs.map((g,i)=>[g.unicode,i]).filter(([cp])=>cp>255);
  const source = `-- Generated by tools/generate-font.mjs. Do not edit. Aileron Regular 0.102, CC0.
-- | All Aileron metadata, lookup and layout for SDF/MSDF and Slug. See API.md.
import "sdf"
import "slug"

module aileron = {
  -- | Atlas dimensions in texels; upload assets/aileron-mtsdf.png as Rgba8Unorm.
  def atlas_size: vec2f32 = ${v([width,height])}
  -- | Atlas texels per em and full encoded distance range in texels.
  def atlas_em_size: f32 = ${f(atlas.atlas.size)}
  def px_range: f32 = ${f(atlas.atlas.distanceRange)}
  -- | Baseline spacing in em and top-down ascender/descender offsets in em.
  def line_height: f32 = ${f(atlas.metrics.lineHeight)}
  def ascender: f32 = ${f(atlas.metrics.ascender)}
  def descender: f32 = ${f(atlas.metrics.descender)}
  -- | Number of explicitly supported Unicode codepoints, including space.
  def glyph_count: i32 = ${glyphs.length}

  -- Internal combined records: one advance and one codepoint index per glyph.
  type internal_record = {advance: f32, plane: vec4f32, uv: vec4f32,
                  bounds: vec4f32, band_transform: vec4f32, bands: vec4i32}
  def internal_glyphs: [${glyphs.length}]internal_record = [
${records}
  ]
  def internal_latin_indices: [256]i32 = [${latin.join(', ')}]
  def internal_index(codepoint: i32) i32 =
    if codepoint >= 0 && codepoint < 256 then internal_latin_indices[codepoint]
${extra.map(([cp,i])=>`    else if codepoint == ${cp} then ${i}`).join('\n')}
    else -1

  def internal_resolved_index(codepoint: i32) i32 =
    if codepoint == 9 || codepoint == 10 || codepoint == 13 || codepoint == 160 then 0
    else let i = internal_index(codepoint) in if i < 0 then ${fallback} else i

  -- | True only for explicitly supported codepoints. NBSP/control aliases are false.
  def has_glyph(codepoint: i32) bool = internal_index(codepoint) >= 0

  -- | Advance in em. Missing -> '?'; TAB -> four spaces; CR/LF -> zero; NBSP -> space.
  def advance(codepoint: i32) f32 =
    if codepoint == 10 || codepoint == 13 then 0.0f32
    else if codepoint == 9 then ${f(glyphs[0].advance*4)}
    else internal_glyphs[internal_resolved_index(codepoint)].advance

  -- | SDF/MSDF/MTSDF metadata, including atlas padding. Controls have empty geometry.
  def sdf_glyph(codepoint: i32) sdf.glyph =
    let g = internal_glyphs[internal_resolved_index(codepoint)] in
    {advance = advance(codepoint), plane = g.plane, uv = g.uv}

  -- | Slug metadata with tight outline bounds. Uses the same advance/fallback policy.
  def slug_glyph(codepoint: i32) slug.glyph =
    let g = internal_glyphs[internal_resolved_index(codepoint)] in
    {advance = advance(codepoint), bounds = g.bounds, band_transform = g.band_transform, bands = g.bands}

  -- | Baselines in pixels, starting at (0,0). LF resets X/advances Y; CR is ignored.
  -- Font size is pixels/em. No kerning, shaping, wrapping or tab stops.
  def layout<[n]>(codepoints: [n]i32, font_size: f32) [n]vec2f32 =
    text.layout(map(|cp: i32| {advance = advance(cp), line_break = cp == 10},
                    codepoints), font_size, line_height)
}
`;
  writeFileSync(resolve(root,'src/aileron.wyn'),source);
  console.log(`Generated unified Aileron module: ${glyphs.length} glyphs, SDF/MSDF + Slug.`);
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url))
  generateFont(resolve(dirname(fileURLToPath(import.meta.url)), '..'));
