// Offline, deterministic atlas build. Requires Node >=18 and msdf-atlas-gen 1.4.
// Usage: node tools/generate.mjs /path/to/msdf-atlas-gen[.exe]
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { resolve, dirname } from 'node:path';
import { spawnSync } from 'node:child_process';
import { createHash } from 'node:crypto';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const generator = process.argv[2];
if (!generator) throw new Error('Pass the path to msdf-atlas-gen 1.4.0.');
const help = spawnSync(generator, ['-help'], { encoding: 'utf8' });
if (!help.stdout?.includes('v1.4.0')) throw new Error('Expected msdf-atlas-gen v1.4.0');
const font = resolve(root, 'assets/Aileron-Regular.otf');
const sha256 = path => createHash('sha256').update(readFileSync(path)).digest('hex');
if (sha256(font) !== '2762f4fc2ebad8323264aea52ffa2260b86c9677493d3ce2dc4f34e5851d2aa2')
  throw new Error('Bundled Aileron Regular 0.102 checksum mismatch.');
// These Latin-1 codepoints are absent in the author's 0.102 font.
const absent = new Set([0xa0, 0xaa, 0xad, 0xb2, 0xb3, 0xb5, 0xb9, 0xba, 0xbc, 0xbd, 0xbe]);
const codepoints = [...Array.from({ length: 95 }, (_, i) => i + 32),
  ...Array.from({ length: 96 }, (_, i) => i + 160).filter(cp => !absent.has(cp)),
  0x152, 0x153, 0x160, 0x161, 0x178, 0x2013, 0x2014, 0x2018, 0x2019,
  0x201c, 0x201d, 0x2022, 0x2026, 0x20ac, 0x2122, 0x2212];
const charset = codepoints.map(cp => `0x${cp.toString(16)}`).join(', ') + '\n';
writeFileSync(resolve(root, 'assets/charset.txt'), charset);
const args = ['-font', font, '-charset', resolve(root, 'assets/charset.txt'),
  '-type', 'mtsdf', '-size', '48', '-pxrange', '8', '-square4', '-yorigin', 'top',
  '-seed', '0', '-threads', '1', '-format', 'png',
  '-imageout', resolve(root, 'assets/aileron-mtsdf.png'),
  '-json', resolve(root, 'assets/aileron-mtsdf.json')];
const run = spawnSync(generator, args, { encoding: 'utf8' });
process.stdout.write(run.stdout ?? '');
process.stderr.write(run.stderr ?? '');
if (run.status !== 0 || /Missing \d+ codepoints/.test(run.stdout + run.stderr))
  throw new Error(`Atlas generation failed (${run.status}).`);
const data = JSON.parse(readFileSync(resolve(root, 'assets/aileron-mtsdf.json'), 'utf8'));
if (data.atlas.yOrigin !== 'top' || data.atlas.type !== 'mtsdf' || data.glyphs.length !== codepoints.length)
  throw new Error('Unexpected atlas metadata.');
const { width, height } = data.atlas;
const glyphs = data.glyphs.sort((a, b) => a.unicode - b.unicode);
const f = n => `${Number(n.toFixed(9))}${Number.isInteger(Number(n.toFixed(9))) ? '.0' : ''}f32`;
const v = ns => `@[${ns.map(f).join(', ')}]`;
const table = glyphs.map(g => {
  const p = g.planeBounds, a = g.atlasBounds;
  return `    { advance = ${f(g.advance)}, plane = ${v(p ? [p.left,p.top,p.right,p.bottom] : [0,0,0,0])}, uv = ${v(a ? [a.left/width,a.top/height,a.right/width,a.bottom/height] : [0,0,0,0])} }`;
}).join(',\n');
const fallback = glyphs.findIndex(g => g.unicode === 63);
// A dense Latin-1 index table makes usual lookups O(1); punctuation is tiny.
const latin = Array.from({ length: 256 }, (_, cp) => glyphs.findIndex(g => g.unicode === cp));
const extra = glyphs.map((g, i) => [g.unicode, i]).filter(([cp]) => cp > 255);
const source = `-- Generated by tools/generate.mjs. Do not edit. Font: Aileron Regular 0.102, CC0.
import "lib"

module aileron = {
  def atlas_size: vec2f32 = ${v([width, height])}
  def atlas_em_size: f32 = ${f(data.atlas.size)}
  def px_range: f32 = ${f(data.atlas.distanceRange)}
  def line_height: f32 = ${f(data.metrics.lineHeight)}
  -- Top-down offsets from the baseline.
  def ascender: f32 = ${f(data.metrics.ascender)}
  def descender: f32 = ${f(data.metrics.descender)}
  def glyph_count: i32 = ${glyphs.length}
  def glyphs: [${glyphs.length}]text.glyph = [
${table}
  ]
  def latin_indices: [256]i32 = [${latin.join(', ')}]
  -- -1 means not present. NBSP is a layout alias for space, not an atlas glyph.
  def index(codepoint: i32) i32 =
    if codepoint >= 0 && codepoint < 256 then latin_indices[codepoint]
${extra.map(([cp, i]) => `    else if codepoint == ${cp} then ${i}`).join('\n')}
    else -1

  def has_glyph(codepoint: i32) bool = index(codepoint) >= 0

  -- Missing glyphs use '?'. LF/CR are invisible; TAB advances four spaces.
  -- NBSP uses space. CR is ignored, so CRLF produces one line break.
  def glyph(codepoint: i32) text.glyph =
    if codepoint == 10 || codepoint == 13 then text.empty_glyph(0.0f32)
    else if codepoint == 9 then text.empty_glyph(${f(glyphs[0].advance * 4)})
    else if codepoint == 160 then glyphs[0]
    else let i = index(codepoint) in glyphs[if i < 0 then ${fallback} else i]

  def layout<[n]>(codepoints: [n]i32, font_size: f32) [n]vec2f32 =
    text.layout(map(|cp: i32| {advance = glyph(cp).advance, line_break = cp == 10},
                    codepoints), font_size, line_height)
}
`;
writeFileSync(resolve(root, 'src/aileron.wyn'), source);
writeFileSync(resolve(root, 'assets/aileron-mtsdf.json'), JSON.stringify(data, null, 2) + '\n');
const manifest = {
  font: 'Aileron Regular', version: '0.102', author: 'Sora Sagano (dot colon)',
  license: 'CC0-1.0', source: 'https://dotcolon.net/fonts/aileron/',
  download: 'https://dotcolon.net/files/fonts/aileron_0102.zip',
  generator: 'msdf-atlas-gen 1.4.0 / MSDFgen 1.13.0',
  generatorSource: 'https://github.com/Chlumsky/msdf-atlas-gen/releases/tag/v1.4',
  options: ['-type mtsdf', '-size 48', '-pxrange 8', '-square4', '-yorigin top', '-seed 0', '-threads 1'],
  glyphCount: glyphs.length, missingLatin1: [...absent].sort((a,b)=>a-b),
  files: Object.fromEntries(['Aileron-Regular.otf','charset.txt','aileron-mtsdf.png','aileron-mtsdf.json']
    .map(name => [name, {sha256: sha256(resolve(root, 'assets', name))}]))
};
writeFileSync(resolve(root, 'assets/provenance.json'), JSON.stringify(manifest, null, 2) + '\n');
console.log(`Generated ${glyphs.length} glyphs in ${width}x${height} MTSDF (RGB=MSDF, A=SDF).`);
