import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import assert from 'node:assert/strict';

const directory = fileURLToPath(new URL('../testfiles/acko_masthead/', import.meta.url));
const sampleVertices = 66808;

// Track order follows the baked curve samples. Shape dimensions are those of
// Acko.TrackData and Track.generators: https://acko.net/cache/combo.min.js
// first, vertex count, profile count, width, arrow, aspect, truncate, shift, edge
const tracks = [
  [0, 2144, 8, 23, 32, .96, 0, 0, 1],
  [2144, 2136, 8, 25, 37, 1, 30, 5.716, 2],
  [4280, 1992, 8, 23, 32, .96, 0, 0, 1],
  [6272, 1992, 8, 25, 37, 1, 30, 5.716, 2],
  [8264, 2536, 8, 23, 32, .96, 0, 0, 1],
  [10800, 2536, 8, 25, 37, 1, 30, 5.716, 2],
  [13336, 3136, 8, 15, 0, 1, 0, 0, 2],
  [16472, 3136, 8, 35, 0, 1, 0, 0, 2],
  [19608, 3880, 8, 30, 0, 1, 0, 0, 2],
  [23488, 4384, 8, 30, 0, 1, 0, 0, 2],
  [27872, 3496, 8, 30, 0, 1, 0, 0, 2],
  [31368, 4080, 8, 30, 0, 1, 0, 0, 2],
  [35448, 3784, 8, 30, 0, 1, 0, 0, 2],
  [39232, 4344, 8, 30, 0, 1, 0, 0, 2],
  [43576, 11616, 16, 80, 0, 1, 0, 0, 2],
  [55192, 11616, 16, 40, 0, 1, 0, 0, 2],
];

const attributes = new Map([
  ['position', 16], ['normal', 16], ['vertex_color', 16],
  ['vert_s', 4], ['track_meta', 16],
].map(([name, stride]) => {
  const bytes = readFileSync(`${directory}${name}.bin`);
  assert(bytes.length >= sampleVertices * stride, `${name}: missing curve samples`);
  return [name, { stride, parts: [bytes.subarray(0, sampleVertices * stride)] }];
}));
const arc = attributes.get('vert_s').parts[0];
const tags = Array(sampleVertices).fill(0);
const ranges = [], shapes = [], indices = [];
let next = sampleVertices, previousEnd = 0;

for (const [track, [first, count, profile, width, arrow, aspect, truncate, shift, edge]] of tracks.entries()) {
  assert.equal(first, previousEnd);
  assert.equal(count % profile, 0);
  assert(count >= profile * 2);
  previousEnd = first + count;
  for (let ring = 0; ring < count / profile; ++ring) {
    const s = arc.readFloatLE((first + ring * profile) * 4);
    if (ring) assert(s > arc.readFloatLE((first + (ring - 1) * profile) * 4));
    for (let corner = 0; corner < profile; ++corner) {
      assert.equal(arc.readFloatLE((first + ring * profile + corner) * 4), s);
      tags[first + ring * profile + corner] = track | (corner << 8);
    }
  }
  ranges.push(first, count / profile, profile, 0);
  shapes.push(arrow, aspect, truncate, shift, width, edge, 0, 0);

  // Roles: body, start center, start bevel, start outline, end outline,
  // arrow base/middle/tip, end bevel, end center.
  function ring(role) {
    const index = next;
    for (let corner = 0; corner < profile; ++corner) {
      for (const { stride, parts } of attributes.values()) {
        parts.push(parts[0].subarray((first + corner) * stride, (first + corner + 1) * stride));
      }
      tags.push(track | (role << 4) | (corner << 8));
    }
    next += profile;
    return index;
  }
  const rows = [ring(1), ring(2), ring(3)];
  for (let offset = 0; offset < count; offset += profile) rows.push(first + offset);
  rows.push(ring(4), ...(arrow ? [ring(5), ring(6), ring(7)] : [ring(8), ring(9)]));
  for (let i = 1; i < rows.length; ++i) {
    const a = rows[i - 1], b = rows[i];
    for (let j = 0; j < profile; ++j) {
      const k = (j + 1) % profile;
      indices.push(a + j, b + k, b + j, a + j, a + k, b + k);
    }
  }
}
assert.equal(previousEnd, sampleVertices);
assert.equal(tags.length, next);
assert(indices.every(index => index < next));

function words(name, values, floating = false) {
  const bytes = Buffer.alloc(values.length * 4);
  values.forEach((value, i) => floating ? bytes.writeFloatLE(value, i * 4) : bytes.writeUInt32LE(value, i * 4));
  writeFileSync(`${directory}${name}.bin`, bytes);
}
for (const [name, { stride, parts }] of attributes) {
  const bytes = Buffer.concat(parts);
  assert.equal(bytes.length, next * stride);
  writeFileSync(`${directory}${name}.bin`, bytes);
}
words('indices', indices);
writeFileSync(`${directory}mesh.wyn`, `-- Generated by scripts/build_masthead_ends.mjs.\ndef masthead_index_count: u32 = ${indices.length}u32\n`);
words('track_vertex', tags);
words('track_ranges', ranges);
words('track_shapes', shapes, true);
console.log(`${tracks.length} tracks, ${next} vertices, ${indices.length / 3} triangles`);
