[package]
name = "treereduce-wyn"
description = "Fast, parallel, syntax-aware program reducer for Wyn"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
keywords = ["program-reducer", "minimization", "test-case-reduction", "wyn"]

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
regex = "1"
tracing-subscriber = { version = "0.3", features = ["json"] }
tree-sitter = "0.25"
tree-sitter-edit = "0.4"
treereduce = "0.4"
tree-sitter-wyn = { path = "../tree-sitter-wyn" }
