// Generated by the Wyn compiler — WGSL backend

@group(0) @binding(0) var<storage, read_write> _buf_0_0: array<f32>;

@group(0) @binding(1) var<storage, read_write> _buf_0_1: array<f32>;

@group(0) @binding(2) var<storage, read_write> _buf_0_2: array<f32>;

fn w_egg_Uhelper_U8_U0(w_p0: f32) -> f32 {
    return (w_p0 * 2.0f);
}

fn w_egg_Uhelper_U9_U1(w_p0: f32, w_p1: f32) -> f32 {
    return (w_p0 + w_p1);
}

@compute @workgroup_size(64, 1, 1)
fn egg_kernel_1(@builtin(global_invocation_id) _wgsl_gid: vec3<u32>, @builtin(local_invocation_id) _wgsl_lid: vec3<u32>, @builtin(num_workgroups) _wgsl_nwg: vec3<u32>) {
    var v3_1: u32 = _wgsl_gid.x;
    loop {
        let v4_1: u32 = (vec2<u32>(u32(0u), u32(64u))).y;
        let v5_1: u32 = (v4_1 + 64u);
        let v6_1: u32 = (v5_1 - 1u);
        let v7_1: u32 = (v6_1 / 64u);
        let v8_1: u32 = max(1u, v7_1);
        let v9_1: bool = (v3_1 < v8_1);
        if !(v9_1) { break; }
        var v11_1: u32 = (v3_1 * 64u);
        var v12_1: f32 = 0.0f;
        loop {
            let v13_1: u32 = (v3_1 * 64u);
            let v14_1: u32 = (v13_1 + 64u);
            let v15_1: u32 = (vec2<u32>(u32(0u), u32(64u))).y;
            let v16_1: u32 = min(v14_1, v15_1);
            let v17_1: bool = (v11_1 < v16_1);
            if !(v17_1) { break; }
            let v18_1: f32 = _buf_0_0[(i32((vec2<u32>(u32(0u), u32(64u))).x)) + (i32(v11_1))];
            let v19_1: f32 = w_egg_Uhelper_U8_U0(v18_1);
            let v20_1: f32 = w_egg_Uhelper_U9_U1(v12_1, v19_1);
            var v22_1: u32 = (v11_1 + 1u);
            var v23_1: f32 = v20_1;
            v11_1 = v22_1;
            v12_1 = v23_1;
        }
        _buf_0_1[(i32((vec2<u32>(u32(0u), u32(64u))).x)) + (i32(v3_1))] = v12_1;
        var v28_1: u32 = (v3_1 + (_wgsl_nwg.x * 64u));
        v3_1 = v28_1;
    }
}

@compute @workgroup_size(1, 1, 1)
fn egg_kernel_10(@builtin(global_invocation_id) _wgsl_gid: vec3<u32>, @builtin(local_invocation_id) _wgsl_lid: vec3<u32>, @builtin(num_workgroups) _wgsl_nwg: vec3<u32>) {
    var v2_1: u32 = 0u;
    var v3_1: f32 = 0.0f;
    loop {
        let v4_1: u32 = (vec2<u32>(u32(0u), u32(64u))).y;
        let v5_1: u32 = (v4_1 + 64u);
        let v6_1: u32 = (v5_1 - 1u);
        let v7_1: u32 = (v6_1 / 64u);
        let v8_1: u32 = max(1u, v7_1);
        let v9_1: bool = (v2_1 < v8_1);
        if !(v9_1) { break; }
        let v11_1: f32 = _buf_0_1[(i32((vec2<u32>(u32(0u), u32(64u))).x)) + (i32(v2_1))];
        let v12_1: f32 = w_egg_Uhelper_U9_U1(v3_1, v11_1);
        var v14_1: u32 = (v2_1 + 1u);
        var v15_1: f32 = v12_1;
        v2_1 = v14_1;
        v3_1 = v15_1;
    }
    _buf_0_2[(i32((vec2<u32>(u32(0u), u32(1u))).x)) + (i32(0u))] = v3_1;
}
